### PR TITLE
python 2 compatibility

### PR DESCRIPTION
**Pull request by toshka**
Previous code did not work on python 2.7.

### CODE REVIEW

**Comment by twidi** [comment]
@toshka: what was the problem? 

this https://travis-ci.org/twidi/django-decorator-include/builds/97083086 shows that it works from 2.6 to 2.7 and 3.2 to 3.5.

Could you please explain? (and by the way you broke 3.2)

**Comment by zkf** [comment]
Hello, @toshka and @twidi. I ran into this issue this morning. The error message from Django was not very helpul in solving it:
```
django.core.exceptions.ImproperlyConfigured: The included urlconf
'<decorator_include.DecoratedPatterns object at 0x7f8233527690>'
does not appear to have any patterns in it. If you see valid patterns 
in the file then the issue is probably caused by a circular import.
```

 The problem arises when the path to the included urlconf is not a unicode string. For instance, a line like this in urls.py will trigger it:

`url(r'^accounts/', decorator_include(my_awesome_decorator, 'allauth.urls')),`

It can be easily fixed by in one of two ways:
1. Replace the urlconf path with a unicode literal: `u'allauth.urls'`
2. Add `from __future__ import unicode_literals` to your urlconf

The reason why the test suite does not fail is that the urlconf there has `from __future__ import unicode_literals`.

One easy fix for this issue would be to simply add a caveat for python 2.x in the README file.

**Comment by jdufresne** [comment]
Hi @toshka and @zkf, if you're still having a Python2 issue, can you test against my PR #12 which uses the compatibility library six bundled with Django? It might fix your issue. It passes all tests on Python2.

**Comment by zkf** [comment]
@jdufresne It works!

**Comment by jdufresne** [comment]
Thanks for testsing!

@twidi How do you feel about closing this in favor of the other PR? The other PR is passing all tests as well as dropping a dependency.

**Comment by wowkin2** [comment]
Propose to describe this workaround (with unicode) somewhere in documentation.
Today I got the same issue (django.core.exceptions.ImproperlyConfigured) on Python 2.7.6

**Comment by toshka** [comment]
@twidi please close this pull request because @jdufresne did the same changes earlier in #12 and merge all PR from @jdufresne

**Comment by twidi** [comment]
As asked, closed in favor of #12

**Pull request closed without merging**
