### PR TITLE
Fix Python 2 compatibility

### PR DESCRIPTION
**Pull request by fixmycode**
The `six.text_type` applies to `str` in Python 3 but to `unicode` in Python 2, that creates an issue for url modules declared as `str` and not `unicode`. The `six.string_type` applies to `basestring` in Python 2 and `str` in Python 3, which coincides with what Django does internally when importing.

### CODE REVIEW

**Comment by twidi** [comment]
Travis is slow as hell! I have other things to do tonight far from the computer, so I'll check this tomorrow.

**Comment by twidi** [comment]
@fixmycode: Your PR doesn't pass the tests, cf https://travis-ci.org/twidi/django-decorator-include/jobs/342028961#L524 But they pass for the branch `bugfixes-1.4`

Could you investigate on this?

**Comment by fixmycode** [comment]
I'll check and get back to you.

**Comment by fixmycode** [comment]
Done, it was a typo, a reminder for me to run the tests locally next time haha.

**Pull request closed without merging**
