### PR TITLE
Updating actions and readme to show support for Django 3.2, 4.0, 4.1, 4.2 and 5.0 including new testing matrix

### PR DESCRIPTION
**Pull request by StevenMapes**
Update the readme and tests to show support or Django 3.2 plus Python 3.10 #88

### CODE REVIEW

**Comment by alvindera97** [comment]
@twidi , hope you're doing well. Just wanted to ask if there's a reason why this hasn't been merged yet. It'll be really helpful if we'd know the source code is compatible with Django 3.2 [and Python 3.10]

Thanks :)

**Comment by StevenMapes** [comment]
This PR now includes updated tests to run the following

Python 3.6 through 3.10 with Django 3.2
Python 3.8 through 3.10 with Django 4.0
Python 3.8 through 3.10 with Django 4.1

**Comment by sergei-maertens** [comment]
@StevenMapes thanks for the efforts you've made so far - Django 4.2 has now also been released and we use this package as a dependency.

Has there been any contact with the maintainer @twidi - is there any timeframe where this will get merged?

**Comment by StevenMapes** [comment]
I've not heard anything myself. I'm using this with Django 4.2 so I'll update this PR again shortly with an another update to the tox matrix and readme

**Comment by StevenMapes** [comment]
I've now updated the test matrix to remove the tests for Python 3.6 but to add in tests for Python 3.11 (Django 4.1.3+ and Django 4.2) as well as matrix for Django 4.2 running against Python 3.8 through 3.11

**Comment by StevenMapes** [comment]
@jdufresne @twidi -If one of you gets time it would be great if you could merge this PR and push another release to Pypi to show that this package works with the current versions of Django and Python

**Comment by StevenMapes** [comment]
I've just updated my PR to include the fix from #90 to remove pkg_resources from the project. This means that it is also now passing unit tests for Python 3.12 and Django 4.2 as well as Python 3.10, 3.11 and 3.12 with Django 5.0

I've included the updated workflow to add these into github actions, I've updated the readme and setup files to show compatibility and I've remove Python 3.7 from the automated tests as it's EOL.

**Comment by StevenMapes** [comment]
I've updated the read me to show the project is able to work with Django 5.1 as well as to update the tox and build.yml to include tests for Django 5.1 and using Python 3.10 through 3.13 and updating the 5.0 test to also use 3.13

**Comment by twidi** [comment]
IT IS HAPPENING !!!

Thanks a lot @StevenMapes , for everyone !!

**Pull request merged**
