### PR TITLE
Upgrade Django 2.0 to the release in Travis CI

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by twidi** [comment]
Hey @jdufresne, Thanks for your work on this. I don't remember who does the packages for pypi? You do or I do?

**Comment by twidi** [comment]
Hey @jdufresne, Thanks for your work on this lib. I don't remember who does the packages for pypi? You do or I do?

**Comment by jdufresne** [comment]
I have not done so in the past. I don't think I have permission.

If you're up for it, please go for it.

**Comment by jdufresne** [comment]
@twidi I just tried to release a new version to PyPI, but looks like I was never given permission. If you're still up for it, I'm happy to help by rolling a release. Cheers.

**Pull request merged**
